apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-accounts-rbac
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abhinayrimilpurty/service-accounts-rbac.git
    targetRevision: main
    path: service-accounts-rbac
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
