apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterRoleBinding.name }}
subjects:
{{- range .Values.clusterRoleBinding.subjects }}
  - kind: {{ .kind }}
    name: {{ .name }}
    namespace: {{ .namespace }}
{{- end }}
roleRef:
  kind: {{ .Values.clusterRoleBinding.roleRef.kind }}
  name: {{ .Values.clusterRoleBinding.roleRef.name }}
  apiGroup: rbac.authorization.k8s.io
