apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.roleBinding.name }}
  namespace: {{ .Values.namespace }}
subjects:
{{- range .Values.roleBinding.subjects }}
  - kind: {{ .kind }}
    name: {{ .name }}
    namespace: {{ .namespace }}
{{- end }}
roleRef:
  kind: {{ .Values.roleBinding.roleRef.kind }}
  name: {{ .Values.roleBinding.roleRef.name }}
  apiGroup: rbac.authorization.k8s.io
